# Generated by Django 5.1.15 on 2026-08-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_extensions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATE", "Criação"),
                    ("UPDATE", "Alteração"),
                    ("DELETE", "Exclusão"),
                    ("MERGE", "Merge"),
                    ("LOGIN", "Login"),
                    ("PERMISSION_CHANGE", "Alteração de permissão"),
                    ("CONFIG_CHANGE", "Alteração de configuração"),
                    ("EXPORT", "Exportação"),
                ],
                max_length=32,
            ),
        ),
    ]
