# Generated by Django 5.1.15 on 2026-08-14 14:44

import apps.core.ids
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_organization_membership_invitation"),
        ("companies", "0002_company_merged_into_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(unique=True, verbose_name="identificador")),
                ("name", models.CharField(max_length=100, verbose_name="nome")),
                ("is_enabled", models.BooleanField(default=True, verbose_name="habilitada")),
                (
                    "retention_policy",
                    models.CharField(
                        choices=[
                            ("PERSIST", "Pode ser armazenado permanentemente"),
                            ("EPHEMERAL_30D", "Expira em 30 dias"),
                        ],
                        default="PERSIST",
                        max_length=16,
                        verbose_name="política de retenção",
                    ),
                ),
                (
                    "rate_limit_per_second",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=6,
                        verbose_name="requisições por segundo",
                    ),
                ),
                (
                    "daily_quota",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Vazio = sem teto.",
                        null=True,
                        verbose_name="cota diária",
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict, verbose_name="configuração")),
            ],
            options={
                "verbose_name": "fonte de dados",
                "verbose_name_plural": "fontes de dados",
                "ordering": ["name"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("rate_limit_per_second__gt", 0)),
                        name="provider_rate_limit_positivo",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CompanySource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(max_length=200, verbose_name="id na fonte")),
                (
                    "raw_payload",
                    models.JSONField(blank=True, default=dict, verbose_name="payload bruto"),
                ),
                (
                    "collected_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="coletado em"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="expira em"),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=2, default=1, max_digits=3, verbose_name="confiança"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="companies.company",
                        verbose_name="empresa",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sources",
                        to="providers.provider",
                    ),
                ),
            ],
            options={
                "verbose_name": "procedência",
                "verbose_name_plural": "procedências",
                "ordering": ["-collected_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "provider"], name="providers_c_company_def545_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "external_id"), name="uniq_fonte_external_id"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("confidence__gte", 0), ("confidence__lte", 1)),
                        name="source_confianca_entre_0_e_1",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProviderUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "period",
                    models.DateField(default=django.utils.timezone.localdate, verbose_name="dia"),
                ),
                (
                    "request_count",
                    models.PositiveIntegerField(default=0, verbose_name="requisições"),
                ),
                ("error_count", models.PositiveIntegerField(default=0, verbose_name="erros")),
                (
                    "estimated_cost",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=10, verbose_name="custo estimado"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="accounts.organization",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usage",
                        to="providers.provider",
                    ),
                ),
            ],
            options={
                "verbose_name": "consumo de fonte",
                "verbose_name_plural": "consumo de fontes",
                "ordering": ["-period"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "organization", "period"),
                        name="uniq_uso_por_fonte_org_dia",
                    )
                ],
            },
        ),
    ]
