# Generated by Django 5.1.15 on 2026-08-14 14:59

import apps.core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_organization_membership_invitation"),
        ("companies", "0002_company_merged_into_and_more"),
        ("geography", "0001_initial"),
        ("providers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Search",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150, verbose_name="nome")),
                ("criteria", models.JSONField(blank=True, default=dict, verbose_name="critérios")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Aguardando"),
                            ("RUNNING", "Em andamento"),
                            ("PARTIALLY_COMPLETED", "Concluída com falhas"),
                            ("COMPLETED", "Concluída"),
                            ("FAILED", "Falhou"),
                            ("CANCELLED", "Cancelada"),
                        ],
                        default="PENDING",
                        max_length=24,
                        verbose_name="situação",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="iniciada em"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="concluída em"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="searches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="criada por",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "busca",
                "verbose_name_plural": "buscas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SearchJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Aguardando"),
                            ("SCHEDULED", "Enfileirado"),
                            ("RUNNING", "Executando"),
                            ("COMPLETED", "Concluído"),
                            ("FAILED", "Falhou"),
                            ("CANCELLED", "Cancelado"),
                        ],
                        default="PENDING",
                        max_length=16,
                        verbose_name="situação",
                    ),
                ),
                ("found_count", models.PositiveIntegerField(default=0, verbose_name="encontradas")),
                ("new_count", models.PositiveIntegerField(default=0, verbose_name="novas")),
                (
                    "duplicate_count",
                    models.PositiveIntegerField(default=0, verbose_name="já conhecidas"),
                ),
                (
                    "review_count",
                    models.PositiveIntegerField(default=0, verbose_name="para revisão"),
                ),
                ("error_count", models.PositiveIntegerField(default=0, verbose_name="erros")),
                (
                    "api_calls",
                    models.PositiveIntegerField(default=0, verbose_name="chamadas à fonte"),
                ),
                ("attempts", models.PositiveIntegerField(default=0, verbose_name="tentativas")),
                ("last_error", models.TextField(blank=True, verbose_name="último erro")),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="iniciado em"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="concluído em"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="search_jobs",
                        to="companies.category",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="search_jobs",
                        to="geography.city",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="search_jobs",
                        to="providers.provider",
                    ),
                ),
                (
                    "search",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="discovery.search",
                        verbose_name="busca",
                    ),
                ),
            ],
            options={
                "verbose_name": "job de busca",
                "verbose_name_plural": "jobs de busca",
                "ordering": ["city__name"],
            },
        ),
        migrations.CreateModel(
            name="SearchResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(max_length=200, verbose_name="id na fonte")),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("EXACT", "Correspondência exata"),
                            ("PROBABLE", "Correspondência provável"),
                            ("POSSIBLE", "Correspondência possível"),
                            ("NEW", "Empresa nova"),
                        ],
                        max_length=16,
                        verbose_name="correspondência",
                    ),
                ),
                (
                    "normalized_payload",
                    models.JSONField(blank=True, default=dict, verbose_name="dados normalizados"),
                ),
                (
                    "matched_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=4,
                        null=True,
                        verbose_name="similaridade",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_results",
                        to="companies.company",
                        verbose_name="empresa",
                    ),
                ),
                (
                    "search_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="discovery.searchjob",
                        verbose_name="job",
                    ),
                ),
            ],
            options={
                "verbose_name": "resultado",
                "verbose_name_plural": "resultados",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="search",
            index=models.Index(
                fields=["organization", "status"], name="discovery_s_organiz_a850e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchjob",
            index=models.Index(fields=["search", "status"], name="discovery_s_search__508ba5_idx"),
        ),
        migrations.AddConstraint(
            model_name="searchjob",
            constraint=models.UniqueConstraint(
                fields=("search", "city", "category", "provider"),
                name="uniq_job_por_busca_cidade_categoria_fonte",
            ),
        ),
        migrations.AddIndex(
            model_name="searchresult",
            index=models.Index(
                fields=["search_job", "match_type"], name="discovery_s_search__41787b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="searchresult",
            constraint=models.UniqueConstraint(
                fields=("search_job", "external_id"), name="uniq_resultado_por_job_external_id"
            ),
        ),
    ]
