# Generated by Django 5.1.15 on 2026-08-14 13:16

import apps.core.ids
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    # `City.centroid` é um PointField: sem a extensão `postgis` já criada, o CREATE TABLE
    # falha. Sem esta aresta no grafo, a ordem entre `core` e `geography` fica por conta do
    # acaso — funciona hoje e quebra numa base nova quando o desempate mudar.
    dependencies = [
        ("core", "0002_extensions"),
    ]

    operations = [
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ibge_code",
                    models.CharField(max_length=2, unique=True, verbose_name="código IBGE"),
                ),
                ("uf", models.CharField(max_length=2, unique=True, verbose_name="UF")),
                ("name", models.CharField(max_length=64, verbose_name="nome")),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("N", "Norte"),
                            ("NE", "Nordeste"),
                            ("SE", "Sudeste"),
                            ("S", "Sul"),
                            ("CO", "Centro-Oeste"),
                        ],
                        max_length=2,
                        verbose_name="região",
                    ),
                ),
            ],
            options={
                "verbose_name": "estado",
                "verbose_name_plural": "estados",
                "ordering": ["name"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("ibge_code__regex", "^\\d{2}$")),
                        name="state_ibge_code_2_digitos",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("uf__regex", "^[A-Z]{2}$")),
                        name="state_uf_2_maiusculas",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ibge_code",
                    models.CharField(max_length=7, unique=True, verbose_name="código IBGE"),
                ),
                ("name", models.CharField(max_length=128, verbose_name="nome")),
                (
                    "normalized_name",
                    models.CharField(
                        editable=False, max_length=128, verbose_name="nome normalizado"
                    ),
                ),
                (
                    "centroid",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326, verbose_name="centroide"
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cities",
                        to="geography.state",
                        verbose_name="estado",
                    ),
                ),
            ],
            options={
                "verbose_name": "município",
                "verbose_name_plural": "municípios",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["normalized_name"], name="geography_c_normali_15affb_idx"),
                    models.Index(
                        fields=["state", "normalized_name"], name="geography_c_state_i_15f954_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("ibge_code__regex", "^\\d{7}$")),
                        name="city_ibge_code_7_digitos",
                    )
                ],
            },
        ),
    ]
