# Generated by Django 5.1.15 on 2026-08-14 14:15

import apps.core.ids
import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    # `core.0002_extensions` é explícita e não transitiva de propósito: o índice GIN de
    # `normalized_name` exige `pg_trgm` e o PointField exige `postgis`. Hoje a aresta viria
    # de graça por `geography`, mas o dia em que a FK para City sair, a garantia sumiria
    # junto — e a falha apareceria só numa base nova.
    dependencies = [
        ("core", "0002_extensions"),
        ("geography", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, verbose_name="nome")),
                (
                    "normalized_name",
                    models.CharField(
                        editable=False, max_length=200, verbose_name="nome normalizado"
                    ),
                ),
                (
                    "legal_name",
                    models.CharField(blank=True, max_length=200, verbose_name="razão social"),
                ),
                (
                    "trade_name",
                    models.CharField(blank=True, max_length=200, verbose_name="nome fantasia"),
                ),
                (
                    "tax_id",
                    models.CharField(blank=True, max_length=14, null=True, verbose_name="CNPJ"),
                ),
                ("description", models.TextField(blank=True, verbose_name="descrição")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Ativa"),
                            ("INACTIVE", "Inativa"),
                            ("CLOSED", "Encerrada"),
                            ("MERGED", "Fundida em outra"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                        verbose_name="situação",
                    ),
                ),
                (
                    "website_status",
                    models.CharField(
                        choices=[
                            ("NOT_CHECKED", "Ainda não verificado"),
                            ("FOUND", "Site identificado"),
                            ("NOT_FOUND", "Site oficial não identificado nas fontes analisadas"),
                        ],
                        default="NOT_CHECKED",
                        max_length=16,
                        verbose_name="situação do site",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=2, null=True, verbose_name="nota"
                    ),
                ),
                ("review_count", models.PositiveIntegerField(default=0, verbose_name="avaliações")),
                (
                    "discovered_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="descoberta em"),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="vista pela última vez em"
                    ),
                ),
                (
                    "data_quality",
                    models.JSONField(blank=True, default=dict, verbose_name="qualidade do dado"),
                ),
            ],
            options={
                "verbose_name": "empresa",
                "verbose_name_plural": "empresas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "slug",
                    models.SlugField(max_length=120, unique=True, verbose_name="identificador"),
                ),
                ("name", models.CharField(max_length=120, verbose_name="nome")),
                (
                    "provider_mapping",
                    models.JSONField(blank=True, default=dict, verbose_name="mapeamento por fonte"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ativa")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="companies.category",
                        verbose_name="categoria pai",
                    ),
                ),
            ],
            options={
                "verbose_name": "categoria",
                "verbose_name_plural": "categorias",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CompanyCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_primary", models.BooleanField(default=False, verbose_name="principal")),
                (
                    "assigned_by",
                    models.CharField(
                        choices=[("PROVIDER", "Fonte"), ("RULE", "Regra"), ("MANUAL", "Manual")],
                        default="PROVIDER",
                        max_length=16,
                        verbose_name="atribuída por",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="company_categories",
                        to="companies.category",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_categories",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "categoria da empresa",
                "verbose_name_plural": "categorias da empresa",
                "ordering": ["-is_primary"],
            },
        ),
        migrations.AddField(
            model_name="company",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="companies",
                through="companies.CompanyCategory",
                to="companies.category",
            ),
        ),
        migrations.CreateModel(
            name="CompanyContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("PHONE", "Telefone"),
                            ("WHATSAPP", "WhatsApp"),
                            ("EMAIL", "E-mail"),
                        ],
                        max_length=16,
                        verbose_name="tipo",
                    ),
                ),
                ("value_raw", models.CharField(max_length=200, verbose_name="valor original")),
                (
                    "value_normalized",
                    models.CharField(max_length=200, verbose_name="valor normalizado"),
                ),
                ("is_primary", models.BooleanField(default=False, verbose_name="principal")),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("UNVERIFIED", "Não verificado"),
                            ("VALID", "Válido"),
                            ("INVALID", "Inválido"),
                        ],
                        default="UNVERIFIED",
                        max_length=16,
                        verbose_name="verificação",
                    ),
                ),
                (
                    "last_verified_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="verificado em"),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=2, default=1.0, max_digits=3, verbose_name="confiança"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="companies.company",
                        verbose_name="empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "contato",
                "verbose_name_plural": "contatos",
                "ordering": ["-is_primary", "kind"],
            },
        ),
        migrations.CreateModel(
            name="CompanySocialProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "network",
                    models.CharField(
                        choices=[
                            ("INSTAGRAM", "Instagram"),
                            ("FACEBOOK", "Facebook"),
                            ("LINKEDIN", "LinkedIn"),
                            ("YOUTUBE", "YouTube"),
                            ("TIKTOK", "TikTok"),
                        ],
                        max_length=16,
                        verbose_name="rede",
                    ),
                ),
                ("url", models.URLField(max_length=500, verbose_name="URL")),
                ("handle", models.CharField(blank=True, max_length=100, verbose_name="perfil")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_profiles",
                        to="companies.company",
                        verbose_name="empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "perfil social",
                "verbose_name_plural": "perfis sociais",
                "ordering": ["network"],
            },
        ),
        migrations.CreateModel(
            name="CompanyWebsite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.URLField(max_length=500, verbose_name="URL")),
                ("domain", models.CharField(max_length=253, verbose_name="domínio")),
                ("is_primary", models.BooleanField(default=False, verbose_name="principal")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNKNOWN", "Não verificado"),
                            ("ONLINE", "No ar"),
                            ("OFFLINE", "Fora do ar"),
                            ("PARKED", "Domínio estacionado"),
                        ],
                        default="UNKNOWN",
                        max_length=16,
                        verbose_name="situação",
                    ),
                ),
                (
                    "last_checked_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="verificado em"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="websites",
                        to="companies.company",
                        verbose_name="empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "site",
                "verbose_name_plural": "sites",
                "ordering": ["-is_primary"],
            },
        ),
        migrations.CreateModel(
            name="CompanyAddress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("street", models.CharField(blank=True, max_length=200, verbose_name="logradouro")),
                ("number", models.CharField(blank=True, max_length=20, verbose_name="número")),
                (
                    "complement",
                    models.CharField(blank=True, max_length=100, verbose_name="complemento"),
                ),
                ("district", models.CharField(blank=True, max_length=100, verbose_name="bairro")),
                ("postal_code", models.CharField(blank=True, max_length=8, verbose_name="CEP")),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326, verbose_name="localização"
                    ),
                ),
                ("is_primary", models.BooleanField(default=False, verbose_name="principal")),
                (
                    "source_ref",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="referência na fonte"
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="company_addresses",
                        to="geography.city",
                        verbose_name="município",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="companies.company",
                        verbose_name="empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "endereço",
                "verbose_name_plural": "endereços",
                "ordering": ["-is_primary"],
                "indexes": [models.Index(fields=["city"], name="companies_c_city_id_aefd31_idx")],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("postal_code", ""), ("postal_code__regex", "^\\d{8}$"), _connector="OR"
                        ),
                        name="address_cep_8_digitos_ou_vazio",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="companycategory",
            constraint=models.UniqueConstraint(
                fields=("company", "category"), name="uniq_categoria_por_empresa"
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["status"], name="companies_c_status_2407e4_idx"),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["website_status"], name="companies_c_website_3c4c1e_idx"),
        ),
        migrations.AddIndex(
            model_name="company",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["normalized_name"], name="company_nome_trgm_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddConstraint(
            model_name="company",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tax_id__isnull", False)),
                fields=("tax_id",),
                name="uniq_company_tax_id_quando_preenchido",
            ),
        ),
        migrations.AddConstraint(
            model_name="company",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("tax_id__isnull", True), ("tax_id__regex", "^\\d{14}$"), _connector="OR"
                ),
                name="company_tax_id_14_digitos",
            ),
        ),
        migrations.AddConstraint(
            model_name="company",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("rating__isnull", True),
                    models.Q(("rating__gte", 0), ("rating__lte", 5)),
                    _connector="OR",
                ),
                name="company_rating_entre_0_e_5",
            ),
        ),
        migrations.AddIndex(
            model_name="companycontact",
            index=models.Index(fields=["value_normalized"], name="companies_c_value_n_440aea_idx"),
        ),
        migrations.AddConstraint(
            model_name="companycontact",
            constraint=models.UniqueConstraint(
                fields=("company", "kind", "value_normalized"),
                name="uniq_contact_por_empresa_tipo_valor",
            ),
        ),
        migrations.AddConstraint(
            model_name="companycontact",
            constraint=models.CheckConstraint(
                condition=models.Q(("confidence__gte", 0), ("confidence__lte", 1)),
                name="contact_confianca_entre_0_e_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="companysocialprofile",
            constraint=models.UniqueConstraint(
                fields=("company", "network", "url"), name="uniq_perfil_por_empresa_rede_url"
            ),
        ),
        migrations.AddIndex(
            model_name="companywebsite",
            index=models.Index(fields=["domain"], name="companies_c_domain_14d482_idx"),
        ),
        migrations.AddConstraint(
            model_name="companywebsite",
            constraint=models.UniqueConstraint(
                fields=("company", "domain"), name="uniq_website_por_empresa_dominio"
            ),
        ),
    ]
