# Generated by Django 5.1.15 on 2026-08-14 17:52

import apps.core.ids
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_organization_membership_invitation"),
        ("companies", "0002_company_merged_into_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "score_snapshot",
                    models.PositiveSmallIntegerField(default=0, verbose_name="score na entrada"),
                ),
                (
                    "last_contacted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="último contato"),
                ),
                (
                    "next_action_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="próxima ação"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leads",
                        to="companies.company",
                        verbose_name="empresa",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="accounts.organization",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="responsável",
                    ),
                ),
            ],
            options={
                "verbose_name": "lead",
                "verbose_name_plural": "leads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("body", models.TextField(verbose_name="texto")),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="autor",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="crm.lead",
                        verbose_name="lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "anotação",
                "verbose_name_plural": "anotações",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Pipeline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="nome")),
                ("is_default", models.BooleanField(default=False, verbose_name="padrão")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "funil",
                "verbose_name_plural": "funis",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PipelineStage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=40, verbose_name="código")),
                ("name", models.CharField(max_length=60, verbose_name="nome")),
                ("position", models.PositiveSmallIntegerField(verbose_name="posição")),
                ("is_terminal", models.BooleanField(default=False, verbose_name="encerra o lead")),
                ("is_won", models.BooleanField(default=False, verbose_name="representa ganho")),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="crm.pipeline",
                        verbose_name="funil",
                    ),
                ),
            ],
            options={
                "verbose_name": "estágio",
                "verbose_name_plural": "estágios",
                "ordering": ["pipeline", "position"],
            },
        ),
        migrations.AddField(
            model_name="lead",
            name="stage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leads",
                to="crm.pipelinestage",
                verbose_name="estágio",
            ),
        ),
        migrations.CreateModel(
            name="SuppressionEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identifier_kind",
                    models.CharField(
                        choices=[
                            ("PHONE", "Telefone"),
                            ("EMAIL", "E-mail"),
                            ("DOMAIN", "Domínio"),
                            ("TAX_ID", "CNPJ"),
                            ("COMPANY", "Empresa"),
                        ],
                        max_length=16,
                        verbose_name="tipo",
                    ),
                ),
                ("identifier_value", models.CharField(max_length=200, verbose_name="valor")),
                ("reason", models.CharField(blank=True, max_length=200, verbose_name="motivo")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suppressions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="registrado por",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "supressão",
                "verbose_name_plural": "supressões",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="título")),
                ("due_at", models.DateTimeField(verbose_name="prazo")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Aberta"),
                            ("DONE", "Concluída"),
                            ("CANCELLED", "Cancelada"),
                        ],
                        default="OPEN",
                        max_length=16,
                        verbose_name="situação",
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="responsável",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="crm.lead",
                        verbose_name="lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "tarefa",
                "verbose_name_plural": "tarefas",
                "ordering": ["due_at"],
            },
        ),
        migrations.CreateModel(
            name="Interaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("CALL", "Ligação"),
                            ("WHATSAPP", "WhatsApp"),
                            ("EMAIL", "E-mail"),
                            ("MEETING", "Reunião"),
                            ("PROPOSAL", "Proposta"),
                            ("NOTE", "Observação"),
                            ("STATUS_CHANGE", "Mudança de estágio"),
                        ],
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="descrição")),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NO_ANSWER", "Sem resposta"),
                            ("ANSWERED", "Atendeu"),
                            ("INTERESTED", "Interessado"),
                            ("NOT_INTERESTED", "Sem interesse"),
                            ("SCHEDULED", "Agendou"),
                        ],
                        max_length=20,
                        verbose_name="resultado",
                    ),
                ),
                (
                    "next_action",
                    models.CharField(blank=True, max_length=200, verbose_name="próxima ação"),
                ),
                (
                    "next_action_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="quando"),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="ocorreu em"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="autor",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="crm.lead",
                        verbose_name="lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "interação",
                "verbose_name_plural": "interações",
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["lead", "-occurred_at"], name="crm_interac_lead_id_b40c2b_idx"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="pipeline",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("organization",),
                name="uniq_funil_padrao_por_organizacao",
            ),
        ),
        migrations.AddConstraint(
            model_name="pipelinestage",
            constraint=models.UniqueConstraint(
                fields=("pipeline", "code"), name="uniq_estagio_por_funil"
            ),
        ),
        migrations.AddConstraint(
            model_name="pipelinestage",
            constraint=models.UniqueConstraint(
                fields=("pipeline", "position"), name="uniq_posicao_por_funil"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["organization", "stage"], name="crm_lead_organiz_99d2d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["organization", "-score_snapshot"], name="crm_lead_organiz_b53f56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["organization", "next_action_at"], name="crm_lead_organiz_1060a1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="lead",
            constraint=models.UniqueConstraint(
                fields=("organization", "company"), name="uniq_lead_por_organizacao_empresa"
            ),
        ),
        migrations.AddIndex(
            model_name="suppressionentry",
            index=models.Index(
                fields=["organization", "identifier_kind", "identifier_value"],
                name="crm_suppres_organiz_c35dd9_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="suppressionentry",
            constraint=models.UniqueConstraint(
                fields=("organization", "identifier_kind", "identifier_value"),
                name="uniq_supressao_por_org_tipo_valor",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["status", "due_at"], name="crm_task_status_947055_idx"),
        ),
    ]
