# Generated by Django 5.1.15 on 2026-08-15 20:08

import apps.core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_organization_membership_invitation"),
        ("companies", "0002_company_merged_into_and_more"),
        ("crm", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, verbose_name="nome")),
                (
                    "description",
                    models.CharField(blank=True, max_length=300, verbose_name="descrição"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="company_lists",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="criada por",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "lista",
                "verbose_name_plural": "listas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CompanyListItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="list_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="adicionada por",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="list_items",
                        to="companies.company",
                        verbose_name="empresa",
                    ),
                ),
                (
                    "company_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="crm.companylist",
                        verbose_name="lista",
                    ),
                ),
            ],
            options={
                "verbose_name": "item da lista",
                "verbose_name_plural": "itens da lista",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="companylist",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="uniq_lista_por_organizacao_nome"
            ),
        ),
        migrations.AddIndex(
            model_name="companylistitem",
            index=models.Index(
                fields=["company_list", "company"], name="crm_company_company_c2ab35_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="companylistitem",
            constraint=models.UniqueConstraint(
                fields=("company_list", "company"), name="uniq_empresa_por_lista"
            ),
        ),
    ]
