# Generated by Django 5.1.15 on 2026-08-15 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_companylist_companylistitem_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interaction",
            options={
                "ordering": ["-occurred_at", "-id"],
                "verbose_name": "interação",
                "verbose_name_plural": "interações",
            },
        ),
    ]
