# Generated by Django 5.1.15 on 2026-08-14 15:58

import apps.core.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0002_company_merged_into_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebsiteScan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OK", "Analisado"),
                            ("UNREACHABLE", "Fora do ar ou inalcançável"),
                            ("BLOCKED", "Recusado pelo guard de SSRF"),
                            ("ERROR", "Erro na análise"),
                        ],
                        max_length=16,
                        verbose_name="situação",
                    ),
                ),
                (
                    "final_url",
                    models.URLField(blank=True, max_length=500, verbose_name="URL final"),
                ),
                (
                    "http_status",
                    models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="HTTP"),
                ),
                ("is_https", models.BooleanField(default=False, verbose_name="HTTPS")),
                (
                    "has_valid_cert",
                    models.BooleanField(default=False, verbose_name="certificado válido"),
                ),
                (
                    "response_time_ms",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="tempo de resposta (ms)"
                    ),
                ),
                (
                    "redirect_count",
                    models.PositiveSmallIntegerField(default=0, verbose_name="redirects"),
                ),
                ("title", models.CharField(blank=True, max_length=300, verbose_name="título")),
                (
                    "meta_description",
                    models.CharField(blank=True, max_length=500, verbose_name="descrição"),
                ),
                ("has_viewport", models.BooleanField(default=False, verbose_name="responsivo")),
                (
                    "has_contact_form",
                    models.BooleanField(default=False, verbose_name="formulário de contato"),
                ),
                ("has_whatsapp", models.BooleanField(default=False, verbose_name="WhatsApp")),
                ("has_booking", models.BooleanField(default=False, verbose_name="agendamento")),
                ("has_cart", models.BooleanField(default=False, verbose_name="carrinho")),
                (
                    "signals",
                    models.JSONField(blank=True, default=dict, verbose_name="outros sinais"),
                ),
                ("error_detail", models.TextField(blank=True, verbose_name="detalhe do erro")),
                (
                    "scanned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="analisado em"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to="companies.company",
                        verbose_name="empresa",
                    ),
                ),
                (
                    "website",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scans",
                        to="companies.companywebsite",
                        verbose_name="site",
                    ),
                ),
            ],
            options={
                "verbose_name": "análise de site",
                "verbose_name_plural": "análises de site",
                "ordering": ["-scanned_at"],
            },
        ),
        migrations.CreateModel(
            name="WebsiteFinding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("NO_HTTPS", "Site sem HTTPS"),
                            ("INVALID_CERT", "Certificado inválido"),
                            ("NO_VIEWPORT", "Não adaptado para celular"),
                            ("SLOW_RESPONSE", "Resposta lenta"),
                            ("NO_CONTACT_CHANNEL", "Sem formulário nem WhatsApp"),
                            ("NO_BOOKING", "Sem agendamento online"),
                            ("SITE_OFFLINE", "Site fora do ar"),
                            ("EXCESSIVE_REDIRECTS", "Redirects em excesso"),
                            ("BLOCKED_TARGET", "Destino recusado pelo guard de SSRF"),
                        ],
                        max_length=32,
                        verbose_name="código",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Informativo"),
                            ("LOW", "Baixa"),
                            ("MEDIUM", "Média"),
                            ("HIGH", "Alta"),
                        ],
                        default="MEDIUM",
                        max_length=8,
                        verbose_name="severidade",
                    ),
                ),
                ("detail", models.TextField(blank=True, verbose_name="detalhe")),
                ("evidence", models.JSONField(blank=True, default=dict, verbose_name="evidência")),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="analysis.websitescan",
                        verbose_name="análise",
                    ),
                ),
            ],
            options={
                "verbose_name": "achado",
                "verbose_name_plural": "achados",
                "ordering": ["severity", "code"],
            },
        ),
        migrations.AddIndex(
            model_name="websitescan",
            index=models.Index(
                fields=["company", "-scanned_at"], name="analysis_we_company_78b9e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="websitescan",
            index=models.Index(fields=["status"], name="analysis_we_status_273e47_idx"),
        ),
        migrations.AddConstraint(
            model_name="websitefinding",
            constraint=models.UniqueConstraint(
                fields=("scan", "code"), name="uniq_achado_por_analise"
            ),
        ),
    ]
