# Generated by Django 5.1.15 on 2026-08-14 17:35

import apps.core.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0001_initial"),
        ("companies", "0002_company_merged_into_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpportunityType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=60, unique=True, verbose_name="código")),
                ("name", models.CharField(max_length=120, verbose_name="nome")),
                ("description", models.TextField(blank=True, verbose_name="descrição")),
                ("rule_code", models.CharField(max_length=60, verbose_name="regra")),
                (
                    "rule_params",
                    models.JSONField(blank=True, default=dict, verbose_name="parâmetros da regra"),
                ),
                (
                    "category_slugs",
                    models.JSONField(blank=True, default=list, verbose_name="categorias"),
                ),
                (
                    "base_confidence",
                    models.DecimalField(
                        decimal_places=2, default=1, max_digits=3, verbose_name="confiança"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ativo")),
            ],
            options={
                "verbose_name": "tipo de oportunidade",
                "verbose_name_plural": "tipos de oportunidade",
                "ordering": ["name"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("base_confidence__gte", 0), ("base_confidence__lte", 1)
                        ),
                        name="tipo_confianca_entre_0_e_1",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Aberta"),
                            ("RESOLVED", "Resolvida"),
                            ("DISMISSED", "Descartada"),
                        ],
                        default="OPEN",
                        max_length=16,
                        verbose_name="situação",
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=2, default=1, max_digits=3, verbose_name="confiança"
                    ),
                ),
                ("evidence", models.JSONField(blank=True, default=dict, verbose_name="evidência")),
                (
                    "detected_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="detectada em"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="resolvida em"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities",
                        to="companies.company",
                        verbose_name="empresa",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opportunities",
                        to="analysis.opportunitytype",
                        verbose_name="tipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "oportunidade",
                "verbose_name_plural": "oportunidades",
                "ordering": ["-detected_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-detected_at"], name="analysis_op_status_12f515_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "type"), name="uniq_oportunidade_por_empresa_tipo"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("confidence__gte", 0), ("confidence__lte", 1)),
                        name="oportunidade_confianca_entre_0_e_1",
                    ),
                ],
            },
        ),
    ]
