# Generated by Django 5.1.15 on 2026-08-14 17:44

import apps.core.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0002_opportunitytype_opportunity"),
        ("companies", "0002_company_merged_into_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoreRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.SlugField(max_length=60, unique=True, verbose_name="código da regra"),
                ),
                ("name", models.CharField(max_length=120, verbose_name="nome")),
                ("points", models.SmallIntegerField(verbose_name="pontos")),
                ("params", models.JSONField(blank=True, default=dict, verbose_name="parâmetros")),
                (
                    "reason_template",
                    models.CharField(
                        help_text="Texto que aparece no breakdown quando a regra pontua.",
                        max_length=200,
                        verbose_name="justificativa",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ativa")),
            ],
            options={
                "verbose_name": "regra de pontuação",
                "verbose_name_plural": "regras de pontuação",
                "ordering": ["-points"],
            },
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("value", models.PositiveSmallIntegerField(default=0, verbose_name="pontuação")),
                ("version", models.CharField(max_length=16, verbose_name="versão das regras")),
                ("computed_at", models.DateTimeField(auto_now=True, verbose_name="calculada em")),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score",
                        to="companies.company",
                        verbose_name="empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "pontuação",
                "verbose_name_plural": "pontuações",
                "ordering": ["-value"],
            },
        ),
        migrations.CreateModel(
            name="ScoreComponent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rule_code", models.CharField(max_length=60, verbose_name="regra")),
                ("points", models.SmallIntegerField(verbose_name="pontos")),
                ("reason", models.CharField(max_length=200, verbose_name="motivo")),
                (
                    "score",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="analysis.score",
                        verbose_name="pontuação",
                    ),
                ),
            ],
            options={
                "verbose_name": "parcela da pontuação",
                "verbose_name_plural": "parcelas da pontuação",
                "ordering": ["-points"],
            },
        ),
        migrations.AddIndex(
            model_name="score",
            index=models.Index(fields=["-value"], name="analysis_sc_value_702704_idx"),
        ),
        migrations.AddConstraint(
            model_name="score",
            constraint=models.CheckConstraint(
                condition=models.Q(("value__gte", 0), ("value__lte", 100)),
                name="score_entre_0_e_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="scorecomponent",
            constraint=models.UniqueConstraint(
                fields=("score", "rule_code"), name="uniq_parcela_por_pontuacao_regra"
            ),
        ),
    ]
